language: php
sudo: false 

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  
before_script: 
  - if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then composer require symfony/http-foundation; fi
  - composer install --prefer-source

script: phpunit --debug --coverage-text

notifications:
  email:
    - dizzda+travis@gmail.com
