language: php
sudo: false 

php:
  - 5.5
  - 5.6
  - 7.1
  - hhvm
  
before_script: composer install --prefer-source

script: phpunit --debug --coverage-text

notifications:
  email:
    - dizzda+travis@gmail.com
